package com.sqeteam.recruitresource.model;
// Generated May 7, 2017 4:09:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EducationLevels generated by hbm2java
 */
public class EducationLevels  implements java.io.Serializable {


     private Integer idEducationLevel;
     private String educationLevel;
     private Set educationalQualificationses = new HashSet(0);
     private Set personses = new HashSet(0);

    public EducationLevels() {
    }

	
    public EducationLevels(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public EducationLevels(String educationLevel, Set educationalQualificationses, Set personses) {
       this.educationLevel = educationLevel;
       this.educationalQualificationses = educationalQualificationses;
       this.personses = personses;
    }
   
    public Integer getIdEducationLevel() {
        return this.idEducationLevel;
    }
    
    public void setIdEducationLevel(Integer idEducationLevel) {
        this.idEducationLevel = idEducationLevel;
    }
    public String getEducationLevel() {
        return this.educationLevel;
    }
    
    public void setEducationLevel(String educationLevel) {
        this.educationLevel = educationLevel;
    }
    public Set getEducationalQualificationses() {
        return this.educationalQualificationses;
    }
    
    public void setEducationalQualificationses(Set educationalQualificationses) {
        this.educationalQualificationses = educationalQualificationses;
    }
    public Set getPersonses() {
        return this.personses;
    }
    
    public void setPersonses(Set personses) {
        this.personses = personses;
    }




}


