package com.sqeteam.recruitresource.model;
// Generated May 7, 2017 4:09:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EmploymentLevels generated by hbm2java
 */
public class EmploymentLevels  implements java.io.Serializable {


     private Integer idLevelsOfEmployment;
     private String employmentLevel;
     private Set experienceses = new HashSet(0);

    public EmploymentLevels() {
    }

	
    public EmploymentLevels(String employmentLevel) {
        this.employmentLevel = employmentLevel;
    }
    public EmploymentLevels(String employmentLevel, Set experienceses) {
       this.employmentLevel = employmentLevel;
       this.experienceses = experienceses;
    }
   
    public Integer getIdLevelsOfEmployment() {
        return this.idLevelsOfEmployment;
    }
    
    public void setIdLevelsOfEmployment(Integer idLevelsOfEmployment) {
        this.idLevelsOfEmployment = idLevelsOfEmployment;
    }
    public String getEmploymentLevel() {
        return this.employmentLevel;
    }
    
    public void setEmploymentLevel(String employmentLevel) {
        this.employmentLevel = employmentLevel;
    }
    public Set getExperienceses() {
        return this.experienceses;
    }
    
    public void setExperienceses(Set experienceses) {
        this.experienceses = experienceses;
    }




}


