package com.sqeteam.recruitresource.model;
// Generated May 7, 2017 4:09:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * JobTitles generated by hbm2java
 */
public class JobTitles  implements java.io.Serializable {


     private Integer idJobTitles;
     private Sectors sectors;
     private String jobTitle;
     private Set experienceses = new HashSet(0);
     private Set personses = new HashSet(0);

    public JobTitles() {
    }

    public JobTitles(Sectors sectors, String jobTitle, Set experienceses, Set personses) {
       this.sectors = sectors;
       this.jobTitle = jobTitle;
       this.experienceses = experienceses;
       this.personses = personses;
    }
   
    public Integer getIdJobTitles() {
        return this.idJobTitles;
    }
    
    public void setIdJobTitles(Integer idJobTitles) {
        this.idJobTitles = idJobTitles;
    }
    public Sectors getSectors() {
        return this.sectors;
    }
    
    public void setSectors(Sectors sectors) {
        this.sectors = sectors;
    }
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }
    public Set getExperienceses() {
        return this.experienceses;
    }
    
    public void setExperienceses(Set experienceses) {
        this.experienceses = experienceses;
    }
    public Set getPersonses() {
        return this.personses;
    }
    
    public void setPersonses(Set personses) {
        this.personses = personses;
    }




}


