package com.sqeteam.recruitresource.model;
// Generated May 7, 2017 4:09:07 PM by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Login generated by hbm2java
 */
public class Login implements java.io.Serializable {

    private Integer idlogin;
    private String email;
    private String password;
    private Set personses = new HashSet(0);

    public Login() {
    }

    public Login(Integer idlogin,String email) {
        this.idlogin=idlogin;
        this.email = email;
    }

    public Login(String email, String password) {
        this.email = email;
        this.password = password;
    }

    public Login(String email, String password, Set personses) {
        this.email = email;
        this.password = password;
        this.personses = personses;
    }

    public Integer getIdlogin() {
        return this.idlogin;
    }

    public void setIdlogin(Integer idlogin) {
        this.idlogin = idlogin;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Set getPersonses() {
        return this.personses;
    }

    public void setPersonses(Set personses) {
        this.personses = personses;
    }

}
