package com.sqeteam.recruitresource.model;
// Generated May 6, 2017 10:46:05 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Login generated by hbm2java
 */
@Entity
@Table(name="login"
    ,catalog="recruitresource"
    , uniqueConstraints = @UniqueConstraint(columnNames="email") 
)
public class Login  implements java.io.Serializable {


     private Integer idlogin;
     private String email;
     private String password;
     private Set<Persons> personses = new HashSet<Persons>(0);

    public Login() {
    }

	
    public Login(String email, String password) {
        this.email = email;
        this.password = password;
    }
    public Login(String email, String password, Set<Persons> personses) {
       this.email = email;
       this.password = password;
       this.personses = personses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idlogin", unique=true, nullable=false)
    public Integer getIdlogin() {
        return this.idlogin;
    }
    
    public void setIdlogin(Integer idlogin) {
        this.idlogin = idlogin;
    }

    
    @Column(name="email", unique=true, nullable=false, length=50)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="password", nullable=false, length=50)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="login")
    public Set<Persons> getPersonses() {
        return this.personses;
    }
    
    public void setPersonses(Set<Persons> personses) {
        this.personses = personses;
    }




}


