package com.sqeteam.recruitresource.model;
// Generated May 7, 2017 4:09:07 PM by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persons generated by hbm2java
 */
public class Persons implements java.io.Serializable {

    private int idUser;
    private EducationLevels educationLevels;
    private Login login;
    private String title;
    private String firstName;
    private String middleName;
    private String lastName;
    private String addressLine1;
    private String addressLine2;
    private String town;
    private String postcode;
    private String alternativeEmail;
    private String personalUrl;
    private byte[] photo;
    private Boolean female;
    private String postcodeStart;
    private String authorityToWorkStatement;
    private String contactPreference;
    private Short noOfGcses;
    private String gcseEnglishGrade;
    private String gcseMathsGrade;
    private Boolean fiveOrMoreGcses;
    private Short noOfAlevels;
    private Short ucasPoints;
    private String studentStatus;
    private String mobile;
    private String landline;
    private Date dob;
    private Short penaltyPoints;
    private String type;
    private Set skillses = new HashSet(0);
    private Set refereeses = new HashSet(0);
    private Set experienceses = new HashSet(0);
    private Set professionalQualificationses = new HashSet(0);
    private Set educationalQualificationses = new HashSet(0);
    private Set jobTitleses = new HashSet(0);

    public Persons() {
    }

    public Persons(Login login, String firstName, String lastName,String type) {
        this.login = login;
        this.firstName = firstName;
        this.lastName = lastName;
        this.type = type;
    }

    public Persons(int idUser, Login login, String firstName, String lastName,String type) {
        this.idUser = idUser;
        this.login = login;
        this.firstName = firstName;
        this.lastName = lastName;
        this.type = type;
    }

    public Persons(int idUser, EducationLevels educationLevels, Login login, String title, String firstName, String middleName, String lastName, String addressLine1, String addressLine2, String town, String postcode, String alternativeEmail, String personalUrl, byte[] photo, Boolean female, String postcodeStart, String authorityToWorkStatement, String contactPreference, Short noOfGcses, String gcseEnglishGrade, String gcseMathsGrade, Boolean fiveOrMoreGcses, Short noOfAlevels, Short ucasPoints, String studentStatus, String mobile, String landline, Date dob, Short penaltyPoints, String type, Set skillses, Set refereeses, Set experienceses, Set professionalQualificationses, Set educationalQualificationses, Set jobTitleses) {
        this.idUser = idUser;
        this.educationLevels = educationLevels;
        this.login = login;
        this.title = title;
        this.firstName = firstName;
        this.middleName = middleName;
        this.lastName = lastName;
        this.addressLine1 = addressLine1;
        this.addressLine2 = addressLine2;
        this.town = town;
        this.postcode = postcode;
        this.alternativeEmail = alternativeEmail;
        this.personalUrl = personalUrl;
        this.photo = photo;
        this.female = female;
        this.postcodeStart = postcodeStart;
        this.authorityToWorkStatement = authorityToWorkStatement;
        this.contactPreference = contactPreference;
        this.noOfGcses = noOfGcses;
        this.gcseEnglishGrade = gcseEnglishGrade;
        this.gcseMathsGrade = gcseMathsGrade;
        this.fiveOrMoreGcses = fiveOrMoreGcses;
        this.noOfAlevels = noOfAlevels;
        this.ucasPoints = ucasPoints;
        this.studentStatus = studentStatus;
        this.mobile = mobile;
        this.landline = landline;
        this.dob = dob;
        this.penaltyPoints = penaltyPoints;
        this.type = type;
        this.skillses = skillses;
        this.refereeses = refereeses;
        this.experienceses = experienceses;
        this.professionalQualificationses = professionalQualificationses;
        this.educationalQualificationses = educationalQualificationses;
        this.jobTitleses = jobTitleses;
    }

    public int getIdUser() {
        return this.idUser;
    }

    public void setIdUser(int idUser) {
        this.idUser = idUser;
    }

    public EducationLevels getEducationLevels() {
        return this.educationLevels;
    }

    public void setEducationLevels(EducationLevels educationLevels) {
        this.educationLevels = educationLevels;
    }

    public Login getLogin() {
        return this.login;
    }

    public void setLogin(Login login) {
        this.login = login;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleName() {
        return this.middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getAddressLine1() {
        return this.addressLine1;
    }

    public void setAddressLine1(String addressLine1) {
        this.addressLine1 = addressLine1;
    }

    public String getAddressLine2() {
        return this.addressLine2;
    }

    public void setAddressLine2(String addressLine2) {
        this.addressLine2 = addressLine2;
    }

    public String getTown() {
        return this.town;
    }

    public void setTown(String town) {
        this.town = town;
    }

    public String getPostcode() {
        return this.postcode;
    }

    public void setPostcode(String postcode) {
        this.postcode = postcode;
    }

    public String getAlternativeEmail() {
        return this.alternativeEmail;
    }

    public void setAlternativeEmail(String alternativeEmail) {
        this.alternativeEmail = alternativeEmail;
    }

    public String getPersonalUrl() {
        return this.personalUrl;
    }

    public void setPersonalUrl(String personalUrl) {
        this.personalUrl = personalUrl;
    }

    public byte[] getPhoto() {
        return this.photo;
    }

    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    public Boolean getFemale() {
        return this.female;
    }

    public void setFemale(Boolean female) {
        this.female = female;
    }

    public String getPostcodeStart() {
        return this.postcodeStart;
    }

    public void setPostcodeStart(String postcodeStart) {
        this.postcodeStart = postcodeStart;
    }

    public String getAuthorityToWorkStatement() {
        return this.authorityToWorkStatement;
    }

    public void setAuthorityToWorkStatement(String authorityToWorkStatement) {
        this.authorityToWorkStatement = authorityToWorkStatement;
    }

    public String getContactPreference() {
        return this.contactPreference;
    }

    public void setContactPreference(String contactPreference) {
        this.contactPreference = contactPreference;
    }

    public Short getNoOfGcses() {
        return this.noOfGcses;
    }

    public void setNoOfGcses(Short noOfGcses) {
        this.noOfGcses = noOfGcses;
    }

    public String getGcseEnglishGrade() {
        return this.gcseEnglishGrade;
    }

    public void setGcseEnglishGrade(String gcseEnglishGrade) {
        this.gcseEnglishGrade = gcseEnglishGrade;
    }

    public String getGcseMathsGrade() {
        return this.gcseMathsGrade;
    }

    public void setGcseMathsGrade(String gcseMathsGrade) {
        this.gcseMathsGrade = gcseMathsGrade;
    }

    public Boolean getFiveOrMoreGcses() {
        return this.fiveOrMoreGcses;
    }

    public void setFiveOrMoreGcses(Boolean fiveOrMoreGcses) {
        this.fiveOrMoreGcses = fiveOrMoreGcses;
    }

    public Short getNoOfAlevels() {
        return this.noOfAlevels;
    }

    public void setNoOfAlevels(Short noOfAlevels) {
        this.noOfAlevels = noOfAlevels;
    }

    public Short getUcasPoints() {
        return this.ucasPoints;
    }

    public void setUcasPoints(Short ucasPoints) {
        this.ucasPoints = ucasPoints;
    }

    public String getStudentStatus() {
        return this.studentStatus;
    }

    public void setStudentStatus(String studentStatus) {
        this.studentStatus = studentStatus;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getLandline() {
        return this.landline;
    }

    public void setLandline(String landline) {
        this.landline = landline;
    }

    public Date getDob() {
        return this.dob;
    }

    public void setDob(Date dob) {
        this.dob = dob;
    }

    public Short getPenaltyPoints() {
        return this.penaltyPoints;
    }

    public void setPenaltyPoints(Short penaltyPoints) {
        this.penaltyPoints = penaltyPoints;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Set getSkillses() {
        return this.skillses;
    }

    public void setSkillses(Set skillses) {
        this.skillses = skillses;
    }

    public Set getRefereeses() {
        return this.refereeses;
    }

    public void setRefereeses(Set refereeses) {
        this.refereeses = refereeses;
    }

    public Set getExperienceses() {
        return this.experienceses;
    }

    public void setExperienceses(Set experienceses) {
        this.experienceses = experienceses;
    }

    public Set getProfessionalQualificationses() {
        return this.professionalQualificationses;
    }

    public void setProfessionalQualificationses(Set professionalQualificationses) {
        this.professionalQualificationses = professionalQualificationses;
    }

    public Set getEducationalQualificationses() {
        return this.educationalQualificationses;
    }

    public void setEducationalQualificationses(Set educationalQualificationses) {
        this.educationalQualificationses = educationalQualificationses;
    }

    public Set getJobTitleses() {
        return this.jobTitleses;
    }

    public void setJobTitleses(Set jobTitleses) {
        this.jobTitleses = jobTitleses;
    }

}
