package com.sqeteam.recruitresource.model;
// Generated May 7, 2017 4:09:07 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sectors generated by hbm2java
 */
public class Sectors  implements java.io.Serializable {


     private Integer idSectors;
     private String sectorTitle;
     private Set jobTitleses = new HashSet(0);
     private Set professionalQualificationses = new HashSet(0);

    public Sectors() {
    }

    public Sectors(String sectorTitle, Set jobTitleses, Set professionalQualificationses) {
       this.sectorTitle = sectorTitle;
       this.jobTitleses = jobTitleses;
       this.professionalQualificationses = professionalQualificationses;
    }
   
    public Integer getIdSectors() {
        return this.idSectors;
    }
    
    public void setIdSectors(Integer idSectors) {
        this.idSectors = idSectors;
    }
    public String getSectorTitle() {
        return this.sectorTitle;
    }
    
    public void setSectorTitle(String sectorTitle) {
        this.sectorTitle = sectorTitle;
    }
    public Set getJobTitleses() {
        return this.jobTitleses;
    }
    
    public void setJobTitleses(Set jobTitleses) {
        this.jobTitleses = jobTitleses;
    }
    public Set getProfessionalQualificationses() {
        return this.professionalQualificationses;
    }
    
    public void setProfessionalQualificationses(Set professionalQualificationses) {
        this.professionalQualificationses = professionalQualificationses;
    }




}


